# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20171215_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_completed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
