# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20171219_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='anecdote',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
