# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 00:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_anecdote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='anecdote',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.Category'),
        ),
    ]
