# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20180201_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts/%Y/%m/%d'),
        ),
    ]
