# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-07 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_goals',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.user_directory_path),
        ),
    ]
